apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
    app.kubernetes.io/name: keycloak
resources:
  - deployment.yaml
  - service.yaml
  - service-account.yaml
images:
  - name: quay.io/keycloak/keycloak
    newTag: 25.0.6
